#!/bin/sh
#IFS=$'\n'
for i in $(ls *.h *.c)
do
	line=$(grep -Enm1 '^\\\*/' $i | awk -F: '{print $1;}')
	cat header > tmp
	if [ -z $line ]
	then
		cat $i >> tmp
	else
		tail $i -n+$(($line + 1)) >> tmp
	fi
	mv tmp $i
done
